{% set name = "gimagereader-qt" %}
{% set version = "3.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/manisandro/gImageReader/releases/download/v{{ version }}/gimagereader-{{ version }}.tar.xz
  sha256: b55cfe9212fa16bf2d5a7ca0fc549454812b265ac7d4aa34697947b20eecf425
  patches:
    - gimagereader-quazip1.patch
    - gimagereader-automoc.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - cmake
    - pkg-config
    - autoconf
    - automake
    - libtool
    - intltool
    - ninja
    - libcap
    - libgomp
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - djvulibre
    - enchant
    - iso-codes
    - libnsl
    - libxmlplusplus
    - libxml2
    - libzip
    - podofo
    - poppler
    - poppler-qt
    - qt
    - qtspell
    - quazip
    - sane
    - tesseract <5
  run:
    - djvulibre
    - enchant
    - iso-codes
    - libnsl
    - libxmlplusplus
    - libxml2
    - libzip
    - podofo
    - poppler
    - poppler-qt
    - qt
    - qtspell
    - quazip
    - sane
    - tesseract

test:
  commands:
    - test -f $PREFIX/bin/gimagereader-qt5

about:
  home: https://github.com/manisandro/gImageReader
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: gImageReader is a simple Gtk/Qt front-end to tesseract-ocr

extra:
  recipe-maintainers:
    - izahn
